# Generated by Django 5.2.6 on 2025-11-06 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresaparceira',
            name='user',
        ),
        migrations.AddField(
            model_name='empresaparceira',
            name='perfil',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_perfil', to='application.perfilusuario'),
            preserve_default=False,
        ),
    ]
