# Generated by Django 5.2.6 on 2025-11-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_empresaparceira_user_empresaparceira_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='vantagem',
            name='comprado',
            field=models.BooleanField(default=False),
        ),
    ]
