# Generated by Django 5.2.6 on 2025-11-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_vantagem_comprado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vantagem',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True),
        ),
    ]
