# Generated by Django 5.2.6 on 2025-11-30 19:34

from django.db import migrations, models


def gerar_codigos_unicos(apps, schema_editor):
    Vantagem = apps.get_model('application', 'Vantagem')

    # Gera códigos únicos para cada linha existente
    for index, v in enumerate(Vantagem.objects.all(), start=1):
        v.codigo = str(index).zfill(6)  # Ex: 000001, 000002, ...
        v.save(update_fields=['codigo'])


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_vantagem_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vantagem',
            name='foto',
        ),
        migrations.AddField(
            model_name='vantagem',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),

        # 👇 ADICIONA ESTA LINHA ANTES DO ALTERFIELD
        migrations.RunPython(gerar_codigos_unicos),

        migrations.AlterField(
            model_name='vantagem',
            name='codigo',
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=6,
                unique=True,
            ),
        ),
    ]
